Ext.define('app.model.credit.TbExamFileInfoModel',{
	extend:'jsf.data.VO',
	fields:[
		{name:'FILE_ID' , type:'string', label:'档案号'},
		{name:'EXAM_YEAR' , type:'int', label:'考核年度'},
		{name:'EXAM_TYPE' , type:'string', label:'考核类别',val:'dict|dict.1038'},
		{name:'CORP_ID' , type:'string', label:'企业ID'},
		{name:'CORP_NUM' , type:'string', label:'经营标志牌号',req:true},//（企业编号）
		{name:'CORP_NAME' , type:'string', label:'企业名称'},
		{name:'CORP_ADD' , type:'string', label:'地址'},
		{name:'LEGAL_PERSON' , type:'string', label:'法人'},
		{name:'CORP_TEL' , type:'string', label:'联系电话',req:true},
		{name:'SERVICE_HOTLINE' , type:'string', label:'企业服务热线',req:true},
		{name:'CORP_TYPE' , type:'string', label:'维修类别',val:'dict|dict.'+app.utils.SysCodes.DB_JYFW},
		{name:'BUSINESS_NUM' , type:'string', label:'经营许可证',req:true},
		{name:'INDUSTRY_CODE' , type:'string', label:'营业执照',req:true},
		{name:'OPEN_DATE' , type:'date', label:'开业时间',dateFormat:'Y-m-d H:i:s'},
		{name:'OLD_EXAM_LEVEL' , type:'string', label:'原质量考核等级'},
		{name:'ECONOMIC_NATURE' , type:'string', label:'经济类型',val:'dict|dict.1035'},
		{name:'REPAIR_TYPES' , type:'string', label:'经营范围'},
		{name:'PLANT_AREA' , type:'float', label:'厂房面积',req:true},
		{name:'PARK_AREA' , type:'float', label:'停车场面积',req:true},
		{name:'ANTEROOM_AREA' , type:'float', label:'接待室面积',req:true},
		{name:'JSFZR_NUM' , type:'int', label:'技术负责人数量',req:true},
		{name:'JSFZE_CZ_NUM' , type:'int', label:'持证（<font color="red">人</font>）',req:true},
		{name:'ZJY_NUM' , type:'int', label:'质检员数量',req:true},
		{name:'ZJY_CZ_NUM' , type:'int', label:'持证（<font color="red">人</font>）',req:true},
		{name:'JX_NUM' , type:'int', label:'机修技术人员数量',req:true},
		{name:'JX_CZ_NUM' , type:'int', label:'持证（<font color="red">人</font>）',req:true},
		{name:'DQ_NUM' , type:'int', label:'电器维修技术人员数量',req:true},
		{name:'DQ_CZ_NUM' , type:'int', label:'持证（<font color="red">人</font>）',req:true},
		{name:'BJ_NUM' , type:'int', label:'钣金维修技术人员数量',req:true},
		{name:'BJ_CZ_NUM' , type:'int', label:'持证（<font color="red">人</font>）',req:true},
		{name:'TQ_NUM' , type:'int', label:'涂漆维修技术人员数量',req:true},
		{name:'TQ_CZ_NUM' , type:'int', label:'持证（<font color="red">人</font>）',req:true},
		{name:'ZZJY_NUM' , type:'int', label:'质量总检验员数量',req:true},
		{name:'ZZJY_CZ_NUM' , type:'int', label:'持证（<font color="red">人</font>）',req:true},
		{name:'CS_NUM' , type:'int', label:'车身维护技术人员数量',req:true},
		{name:'CS_CZ_NUM' , type:'int', label:'持证（<font color="red">人</font>）',req:true},
		{name:'LPG_NUM' , type:'int', label:'LPG/危运维修技术人员数量',req:true},
		{name:'LPG_CZ_NUM' , type:'int', label:'持证（<font color="red">人</font>）',req:true},
		{name:'YW_NUM' , type:'int', label:'业务接待人员数量',req:true},
		{name:'YW_CZ_NUM' , type:'int', label:'持证（<font color="red">人</font>）',req:true},
		{name:'JG_NUM' , type:'int', label:'价格核算人员数量',req:true},
		{name:'JG_CZ_NUM' , type:'int', label:'持证（<font color="red">人</font>）',req:true},
		{name:'GL_NUM' , type:'int', label:'管理负责人员数量',req:true},
		{name:'GL_CZ_NUM' , type:'int', label:'持证（<font color="red">人</font>）',req:true},
		{name:'QT_NUM' , type:'int', label:'其它从业人员数量',req:true},
		{name:'QT_CZ_NUM' , type:'int', label:'持证（<font color="red">人</font>）',req:true},
		{name:'TYSB_NUM' , type:'int', label:'通用设备数',req:true},
		{name:'ZYSB_NUM' , type:'int', label:'专用设备数',req:true},
		{name:'JCSB_NUM' , type:'int', label:'检测设备数',req:true},
		{name:'JLSB_NUM' , type:'int', label:'计量设备数',req:true},
		{name:'ZYSGGJ_NUM' , type:'int', label:'主要手工工具数',req:true},
		{name:'WXSB_NUM' , type:'int', label:'外协设备数',req:true},
		{name:'QTSB_NUM' , type:'int', label:'其它设备数',req:true},
		{name:'ZHCDX_NUM' , type:'int', label:'整车大修',req:true},
		{name:'ZCDX_NUM' , type:'int', label:'总成大修',req:true},
		{name:'EJWH_NUM' , type:'int', label:'二级维护',req:true},
		{name:'CLXX_NUM' , type:'int', label:'车辆小修',req:true},
		{name:'ZXWX_NUM' , type:'int', label:'专项维修',req:true},
		{name:'JY_NUM' , type:'int', label:'救援',req:true},
		{name:'WXCZ_NUM' , type:'float', label:'维修产值',req:true},
		{name:'WXLR_NUM' , type:'float', label:'维修利润',req:true},
		{name:'SJSJ_NUM' , type:'float', label:'上缴国家税金',req:true},
		{name:'GSSG_NUM' , type:'int', label:'工伤事故（ <font color="red">次</font>）',req:true},
		{name:'HZSG_NUM' , type:'int', label:'火灾事故（ <font color="red">次</font>）',req:true},
		{name:'YDSG_NUM' , type:'int', label:'用电事故（ <font color="red">次</font>）',req:true},
		{name:'QTSG_NUM' , type:'int', label:'其他事故（ <font color="red">次</font>）',req:true},
		{name:'SSRS_NUM' , type:'int', label:'受伤人数（ <font color="red">人</font>）',req:true},
		{name:'SWRS_NUM' , type:'int', label:'死亡人数（ <font color="red">人</font>）',req:true},
		{name:'JJSS_NUM' , type:'float', label:'经济损失（ <font color="red">元</font>）',req:true},
		{name:'HBHS_NUM' , type:'float', label:'环保回收废机油（ <font color="red">吨</font>）',req:true},
		{name:'FJLT_NUM' , type:'int', label:'废旧轮胎（ <font color="red">条</font>）',req:true},
		{name:'FJXDC_NUM' , type:'int', label:'废旧蓄电池（ <font color="red">个</font>）',req:true},
		{name:'FWZLSJ_NUM' , type:'int', label:'服务质量事件（ <font color="red">件</font>）',req:true},
		{name:'TB_NUM' , type:'int', label:'被管理部门通报（ <font color="red">件</font>）',req:true},
		{name:'KHTS_NUM' , type:'int', label:'客户投诉（ <font color="red">件</font>）',req:true},
		{name:'MYD_NUM' , type:'float', label:'投诉客户满意率（ <font color="red">%</font>）',req:true},
		{name:'YZTS_NUM' , type:'int', label:'有责投诉（ <font color="red">件</font>）',req:true},
		{name:'IS_UPLOAD' , type:'string', label:'是否提交',val:'dict|dict.'+app.utils.SysCodes.YESNO},
		{name:'UPLOAD_OPER' , type:'string', label:'提交人'},
		{name:'UPLOAD_DATE' , type:'date', label:'提交时间',dateFormat:'Y-m-d H:i:s'},
		{name:'IS_ZJ_EXAM' , type:'string', label:'是否专家初评',val:'dict|dict.'+app.utils.SysCodes.YESNO},
		{name:'ZJ_EXAM_LEVEL' , type:'string', label:'专家初评等级'},
		{name:'ZJ_OPER' , type:'string', label:'专家组'},
		{name:'JZ_DATE' , type:'date', label:'专家初评时间',dateFormat:'Y-m-d H:i:s'},
		{name:'IS_FIRST_EXAM' , type:'string', label:'是否初评',val:'dict|dict.'+app.utils.SysCodes.YESNO},
		{name:'FIRST_EXAM_LEVEL' , type:'string', label:'初评等级'},
		{name:'FIRST_OPER' , type:'string', label:'初评人'},
		{name:'FIRST_DATE' , type:'date', label:'初评时间',dateFormat:'Y-m-d H:i:s'},
		{name:'IS_SEC_EXAM' , type:'string', label:'是否复评',val:'dict|dict.'+app.utils.SysCodes.YESNO},
		{name:'SEC_EXAM_LEVEL' , type:'string', label:'复评等级'},
		{name:'SEC_OPER' , type:'string', label:'复评人'},
		{name:'SEC_DATE' , type:'date', label:'复评时间',dateFormat:'Y-m-d H:i:s'},
		{name:'IS_GS' , type:'string', label:'是否公示'},
		{name:'GS_DATE' , type:'date', label:'公示时间',dateFormat:'Y-m-d H:i:s'},
		{name:'IS_GB' , type:'string', label:'是否公布'},
		{name:'GB_DATE' , type:'date', label:'公布时间',dateFormat:'Y-m-d H:i:s'}
	]
});