Ext.define('app.model.corp.TbCorpInfoModel',{
	extend:'jsf.data.VO',
	fields:[
		{name:'CORP_ID' , type:'string', label:'企业ID'},
		{name:'CORP_NUM' , type:'string', label:'企业编号',req:true},
		{name:'CORP_NAME' , type:'string', label:'企业名称',req:true},
		{name:'RUN_ADD_POST' , type:'string', label:'经营地址邮编'},
		{name:'COM_ADD' , type:'string', label:'通信地址'},
		{name:'COM_POST' , type:'string', label:'通信地址邮编'},
		{name:'CORP_AREA' , type:'string', label:'所属辖区'},
		{name:'CORP_ADD' , type:'string', label:'企业地址'},
		{name:'RUN_ADD' , type:'string', label:'经营地址'},
		{name:'REPAIR_TYPES' , type:'string', label:'维修项目种类'},
		{name:'REPAIR_TYPES_' , type:'string', label:'维修项目种类'},
		{name:'CORP_TYPE' , type:'string', label:'经营范围',req:true,val:'dict|dict.'+app.utils.SysCodes.DB_JYFW},
		{name:'CORP_STYPE' , type:'string', label:'兼营范围',val:'dict|dict.'+app.utils.SysCodes.DB_JIYFW},
		{name:'ECONOMIC_NATURE' , type:'string', label:'经济性质'},
		{name:'ACCOUNT_TYPE' , type:'string', label:'核算形式',val:'dict|dict.'+app.utils.SysCodes.ACCOUNT_TYPE},
		{name:'EMAIL' , type:'string', label:'电子邮箱'},
		{name:'BOUND' , type:'string', label:'特约品牌'},
		{name:'ADMIN_DEPT' , type:'string', label:'主管部门'},
		{name:'SERVICE_HOTLINE' , type:'string', label:'企业联系电话'},
		{name:'WEB_SITE' , type:'string', label:'企业网址'},
		{name:'CHARGE_PERSON' , type:'string', label:'企业负责人'},
		{name:'COPR_TEL' , type:'string', label:'联系电话'},
		{name:'LEGAL_PERSON' , type:'string', label:'法人代表'},
		{name:'LEGAL_TEL' , type:'string', label:'法人手机'},
		{name:'CONTACTS' , type:'string', label:'联系人'},
		{name:'CONTACTS_TEL' , type:'string', label:'联系人手机'},
		{name:'TECHNOLOGY_PERSON' , type:'string', label:'技术负责人'},
		{name:'PHONE' , type:'string', label:'固定电话'},
		{name:'FINAL_PERSON' , type:'string', label:'财务负责人'},
		{name:'FAX_NUM' , type:'string', label:'传真号码'},
		{name:'QUALITY_PERSON' , type:'string', label:'质量负责人'},
		{name:'REGIST_FUNDS' , type:'float', label:'注册资金(万元)'},
		{name:'FIX_FUNDS' , type:'float', label:'固定资产(万元)'},
		{name:'FLOW_FUNDS' , type:'float', label:'流动资金(万元)'},
		{name:'PLANT_AREA' , type:'float', label:'作业厂房面积(㎡)'},
		{name:'PARK_AREA' , type:'float', label:'停车场面积(㎡)'},
		{name:'ANTEROOM_AREA' , type:'float', label:'接待室面积(㎡)'},
		{name:'TRAIN_AREA' , type:'float', label:'培训室面积(㎡)'},
		{name:'INDUSTRY_ORGAN' , type:'string', label:'工商批准机关'},
		{name:'INDUSTRY_CODE' , type:'string', label:'工商注册号码'},
		{name:'CERT_ORGAN' , type:'string', label:'发证机关'},
		{name:'FIRST_CERT_TIME' , type:'date', label:'首次发证时间',dateFormat:'Y-m-d H:i:s'},
		{name:'CERT_DATE' , type:'date', label:'发证日期',dateFormat:'Y-m-d H:i:s'},
		{name:'VALID_START_DATE' , type:'date', label:'有效开始日期',dateFormat:'Y-m-d H:i:s'},
		{name:'VALID_END_DATE' , type:'date', label:'有效结束日期',dateFormat:'Y-m-d H:i:s'},
		{name:'TAX_NUM' , type:'string', label:'税务登记号'},
		{name:'BUSINESS_NUM' , type:'string', label:'道路经营许可证号'},
		{name:'REMARK' , type:'string', label:'备注'},
		{name:'BIG_STATION' , type:'int', label:'大车工位(个)'},
		{name:'SMALL_STATION' , type:'int', label:'小车工位(个)'},
		{name:'IS_SEC_MAINTAIN' , type:'string', label:'是否二级维护定点厂'},
		{name:'IS_LPG' , type:'string', label:'是否LPG定点维修厂'},
		{name:'IS_WYCL' , type:'string', label:'是否危运车辆维修'},
		{name:'IS_TAX' , type:'string', label:'是否出租车定点维护厂'},
		{name:'IS_DZXHC' , type:'string', label:'大中型货车'},
		{name:'IS_DZXKC' , type:'string', label:'大中型客车'},
		{name:'IS_XXC' , type:'string', label:'小型车'},
		{name:'IS_WQC' , type:'string', label:'尾气资质'},
		{name:'IS_JLC' , type:'string', label:'教练车维护'},
		{name:'IS_S4' , type:'string', label:'是否4S店'},
		{name:'IS_CHAIN' , type:'string', label:'是否连锁经营'},
		{name:'IS_HONEST' , type:'string', label:'是否诚信优质'},
		{name:'STATUS' , type:'string', label:'企业状态',val:'dict|dict.'+app.utils.SysCodes.CORP_STATUS},
		{name:'IS_BLACKLIST' , type:'string', label:'是否黑名单'},
		{name:'UPDATE_DATE' , type:'date', label:'修改日期',dateFormat:'Y-m-d H:i:s'},
		{name:'OPEN_DATE',type:'string',label:'开业时间'},
		{name:'CREATE_QUATO_COUNT' , type:'int', label:'建档配额'},
		{name:'UPLOAD_QUATO_COUNT' , type:'int', label:'维修记录配额'},
		{name:'SEARCH_QUATO_COUNT' , type:'int', label:'查询配额'}
	]
});