Ext.define('app.model.corp.TcCorpInfoModel',{
	extend:'jsf.data.VO',
	fields:[
		{name:'CORP_ID' , type:'string', label:'企业ID'},
		{name:'CORP_NUM' , type:'string', label:'企业编号'},
		{name:'CORP_NAME' , type:'string', label:'企业名称',req:true},
		{name:'RUN_ADD_POST' , type:'string', label:'经营地址邮编'},
		{name:'COM_ADD' , type:'string', label:'通信地址'},
		{name:'COM_POST' , type:'string', label:'通信地址邮编'},
		{name:'CORP_AREA' , type:'string', label:'所属辖区'},
		{name:'CORP_ADD' , type:'string', label:'企业地址'},
		{name:'RUN_ADD' , type:'string', label:'经营地址'},
		{name:'CORP_TYPE' , type:'string', label:'企业类型',req:true,val:'dict|dict.'+app.utils.SysCodes.DB_JYFW},
		{name:'CORP_STYPE' , type:'string', label:'兼营范围',val:'dict|dict.'+app.utils.SysCodes.DB_JIYFW},
		{name:'ECONOMIC_NATURE' , type:'string', label:'经济性质',val:'dict|dict.'+app.utils.SysCodes.ECONOMIC_NATURE},
		{name:'ACCOUNT_TYPE' , type:'string', label:'核算形式',val:'dict|dict.'+app.utils.SysCodes.ACCOUNT_TYPE},
		{name:'EMAIL' , type:'string', label:'电子邮箱'},
		{name:'BOUND' , type:'string', label:'特约品牌'},
		{name:'ADMIN_DEPT' , type:'string', label:'主管部门'},
		{name:'SERVICE_HOTLINE' , type:'string', label:'企业联系电话'},
		{name:'WEB_SITE' , type:'string', label:'企业网址'},
		{name:'CHARGE_PERSON' , type:'string', label:'企业负责人'},
		{name:'COPR_TEL' , type:'string', label:'联系电话'},
		{name:'LEGAL_PERSON' , type:'string', label:'法人代表'},
		{name:'LEGAL_TEL' , type:'string', label:'负责人手机'},
		{name:'CONTACTS' , type:'string', label:'联系人',req:true},
		{name:'CONTACTS_TEL' , type:'string', label:'联系人手机',req:true},
		{name:'TECHNOLOGY_PERSON' , type:'string', label:'技术负责人'},
		{name:'PHONE' , type:'string', label:'固定电话'},
		{name:'FINAL_PERSON' , type:'string', label:'财务负责人'},
		{name:'FAX_NUM' , type:'string', label:'传真号码'},
		{name:'CERT_ORGAN' , type:'string', label:'发证机关',req:true},
		{name:'FIRST_CERT_TIME' , type:'date', label:'首次发证时间',dateFormat:'Y-m-d H:i:s'},
		{name:'CERT_DATE' , type:'date', label:'发证日期',dateFormat:'Y-m-d H:i:s',req:true},
		{name:'VALID_START_DATE' , type:'date', label:'有效开始日期',dateFormat:'Y-m-d H:i:s',req:true},
		{name:'VALID_END_DATE' , type:'date', label:'有效结束日期',dateFormat:'Y-m-d H:i:s',req:true},
		{name:'TAX_NUM' , type:'string', label:'税务登记号'},
		{name:'BUSINESS_NUM' , type:'string', label:'道路经营许可证号',req:true},
		{name:'REMARK' , type:'string', label:'备注'},
		{name:'STATUS' , type:'string', label:'企业状态',val:'dict|dict.'+app.utils.SysCodes.CORP_STATUS},
		{name:'IS_BLACKLIST' , type:'string', label:'是否黑名单'},
		{name:'UPDATE_DATE' , type:'date', label:'修改日期',dateFormat:'Y-m-d H:i:s'},
	]
});